version: "3.8"
services:

  # postgres database
  db:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB : ${DB_NAME}
    ports:
      - "5432:5432"
    container_name: postgres_db

  # python-api 
  backend-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    image: python_backend_api:petrolhead_django
    container_name: petrolhead_django
    command: gunicorn --bind 0.0.0.0:8001 car_inventory.wsgi:application
    depends_on:
      - db