services:
 # A web service that builds from a Dockerfile
  - type: web
    runtime: image
    name: backend-api
    plan: free
    region: oregon
    autoDeploy: false
    image: 
      url: docker.io/asandah/car_inventory:latest
    healthCheckPath: /
    startCommand: gunicorn --bind 0.0.0.0:8001 car_inventory.wsgi:application

databases:
  - name: elephant
    postgresMajorVersion: "16" 
    region: oregon
    plan: free 
    databaseName: petrol_head_db 
    user: asandah 
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
