# Generated by Django 5.0.2 on 2024-03-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('founder', models.TextField()),
                ('year_founded', models.IntegerField()),
                ('headquarters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('model_year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission_type', models.TextField()),
                ('engine_position', models.TextField(default='Front')),
                ('engine_litre', models.CharField(max_length=5)),
                ('fuel_consumption', models.CharField(max_length=10)),
                ('fuel_type', models.TextField(default='petrol')),
                ('cylinder_layout', models.CharField(max_length=10)),
                ('horsepower', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('top_speed', models.IntegerField()),
                ('image_url', models.URLField()),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_models', to='german_collection.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.TextField()),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='segments', to='german_collection.carmodel')),
            ],
        ),
    ]
