# Generated by Django 5.0.2 on 2024-02-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_models', to='german_collection.manufacturer'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='car_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='segments', to='german_collection.carmodel'),
        ),
    ]
