# Generated by Django 5.0.2 on 2024-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german_collection', '0002_alter_carmodel_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine_position',
            field=models.TextField(default='Front'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='horsepower',
            field=models.IntegerField(blank=True),
        ),
    ]
