# Generated by Django 5.0.2 on 2024-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german_collection', '0003_alter_carmodel_engine_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='horsepower',
            field=models.IntegerField(null=True),
        ),
    ]
