name: Build and share Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
    publish_docker_image:
        name: Docker
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build image
            run: docker build --platform=linux/amd64 -t asandah/${{secrets.DOCKERHUB_REPO_NAME}} .
          - name: Push image 
            run: |
              docker login -u asandah -p ${{secrets.DOCKER_HUB_TOKEN}} 
              docker push asandah/${{secrets.DOCKERHUB_REPO_NAME}}
