name: Build and share Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
    publish_docker_image:
        name: Docker
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build image
            run: docker build -t ${{secrets.DOCKER_USERAME}}/${{secrets.DOCKERHUB_REPO_NAME}} .
          - name: Push image 
            run: |
              docker login -u ${{secrets.DOCKER_USERAME}} -p ${{secrets.DOCKER_HUB_TOKEN}} 
              docker push ${{secrets.DOCKER_USERAME}}/${{secrets.DOCKERHUB_REPO_NAME}}
